In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score

import pandas as pd
import numpy as np
import pickle

In [ ]:
path = 'DataMarch.csv'
df = pd.read_csv(path)



In [ ]:
df.head()

Age  Gender  AppliedAmount  Amount  Interest  LoanDuration  MonthlyPayment  \
0   20     0.0       319.5582  319.56      40.0             1             0.0   
1   49     1.0       319.5582  319.56      30.0            20             0.0   
2   19     0.0       319.5582   70.30      49.0             2             0.0   
3   41     0.0       191.7349  191.75      30.0            18             0.0   
4   19     0.0       115.0410   19.17      49.0             1             0.0   

   UseOfLoan  Education  MaritalStatus  ...  Target  Status  \
0          0        3.0            3.0  ...       1       1   
1          2        2.0            4.0  ...       1       1   
2          3        2.0            2.0  ...       1       1   
3          3        5.0            1.0  ...       1       1   
4          2        2.0            2.0  ...       1       1   

   PrincipalWriteOffs  InterestAndPenaltyWriteOffs  \
0                 0.0                          0.0   
1                 0.0                          0.0   
2                 0.0                          0.0   
3                 0.0                          0.0   
4                 0.0                          0.0   

   PrincipalDebtServicingCost  InterestAndPenaltyDebtServicingCost        EMI  \
0                         0.0                                 0.00  32.745603   
1                         0.0                                 0.00   8.010331   
2                         0.0                                 0.00  21.138012   
3                         0.0                                54.14   4.816621   
4                         0.0                                 0.00  12.317211   

   Risk       ELA       ROI  
0   0.5  0.240099  0.009067  
1   0.5  0.123593  0.006730  
2   0.5  0.156880  0.002239  
3   0.5  0.214272  0.003926  
4   0.5  0.137941  0.000406  

[5 rows x 27 columns]

In [ ]:
df.shape

(27847, 27)

In [ ]:
X_features = ['Gender','Status','Education','EmploymentStatus','MaritalStatus','HomeOwnershipType','UseOfLoan','Amount','Interest','LoanDuration','IncomeTotal','LiabilitiesTotal','DebtToIncome','FreeCash']

In [ ]:
df_X = df[X_features]

In [ ]:
df_X

Gender  Status  Education  EmploymentStatus  MaritalStatus  \
0         0.0       1        3.0                 1            3.0   
1         1.0       1        2.0                 1            4.0   
2         0.0       1        2.0                 1            2.0   
3         0.0       1        5.0                 1            1.0   
4         0.0       1        2.0                 1            2.0   
...       ...     ...        ...               ...            ...   
27842     0.0       2        3.0                 1            3.0   
27843     0.0       2        3.0                 1            3.0   
27844     0.0       1        3.0                 2            1.0   
27845     1.0       2        5.0                 1            1.0   
27846     1.0       1        4.0                 1            3.0   

       HomeOwnershipType  UseOfLoan   Amount  Interest  LoanDuration  \
0                    0.0          0   319.56     40.00             1   
1                    0.0          2   319.56     30.00            20   
2                    0.0          3    70.30     49.00             2   
3                    0.0          3   191.75     30.00            18   
4                    0.0          2    19.17     49.00             1   
...                  ...        ...      ...       ...           ...   
27842                5.0          1  3000.00     31.01            60   
27843                1.0          3  3000.00     18.25            60   
27844                1.0          1  2500.00     24.83            60   
27845                4.0          2  3000.00     17.74            60   
27846                2.0          1  3000.00     30.50            60   

       IncomeTotal  LiabilitiesTotal  DebtToIncome  FreeCash  
0          26500.0              0.00          0.00      0.00  
1           6200.0              0.00          0.00      0.00  
2          12000.0              0.00          0.00      0.00  
3          22000.0              0.00          0.00      0.00  
4           8700.0              0.00          0.00      0.00  
...            ...               ...           ...       ...  
27842       1400.0            500.00          7.69    792.32  
27843       2265.0           1777.46         31.58    520.67  
27844       2500.0           1350.00          3.22   1069.58  
27845        540.0            732.05         44.35     50.49  
27846        500.0            531.03         35.03     74.86  

[27847 rows x 14 columns]

In [ ]:
# 1 Primary education 2 Basic education 3 Vocational education 4 Secondary education 5 Higher education
df['Education'].unique()

array([3., 2., 5., 4., 1.])

In [ ]:
# 1 Married 2 Cohabitant 3 Single 4 Divorced 5 Widow
df['MaritalStatus'].unique()

array([3., 4., 2., 1., 5.])

In [ ]:
# ????
df['Status'].unique()

array([1, 2, 0])

In [ ]:
# 0 Male 1 Woman ??????  
df['Gender'].unique()

array([0., 1.])

In [ ]:
# 0 Homeless 1 Owner 2 Living with parents 3 Tenant, pre-furnished property 4 Tenant, unfurnished property 5 Council house 6 Joint tenant 7 Joint ownership 8 Mortgage 9 Owner with encumbrance 10 Other
df['HomeOwnershipType'].unique()

array([0., 4., 2., 1., 3., 5., 8., 6., 7., 9.])

In [ ]:
df['EmploymentStatus'].unique()

array([1, 2, 0])

In [ ]:
# 0 Loan consolidation 1 Real estate 2 Home improvement 3 Business
df['UseOfLoan'].unique()

array([0, 2, 3, 1])

In [ ]:
Y_Classification_features = ['Target']
Y_Regression_features = ['EMI', 'ELA', 'ROI']
df_y_classification = df[Y_Classification_features]
df_y_regression = df[Y_Regression_features]

In [ ]:
df_y_classification

Target
0           1
1           1
2           1
3           1
4           1
...       ...
27842       1
27843       0
27844       1
27845       1
27846       1

[27847 rows x 1 columns]

In [ ]:
df_y_regression

EMI       ELA       ROI
0      32.745603  0.240099  0.009067
1       8.010331  0.123593  0.006730
2      21.138012  0.156880  0.002239
3       4.816621  0.214272  0.003926
4      12.317211  0.137941  0.000406
...          ...       ...       ...
27842  77.525001  0.093176  0.067752
27843  45.625870  0.090808  0.039758
27844  51.729187  0.094610  0.045115
27845  44.351143  0.086908  0.038639
27846  76.250001  0.087832  0.066633

[27847 rows x 3 columns]

# Classification

In [ ]:
# For the Classification Model
X_train, X_test, y_train_clf, y_test_clf = train_test_split(df_X, df_y_classification, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [ ]:
# Define the pipeline
pipeline_clf = Pipeline(steps=[('scaler', StandardScaler()),
                           ('model', model)])



In [ ]:
# Fit the pipeline on the training data
pipeline_clf.fit(X_train, y_train_clf)




/usr/local/lib/python3.9/dist-packages/sklearn/pipeline.py:405: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)


Pipeline(steps=[('scaler', StandardScaler()),
                ('model', RandomForestClassifier(random_state=42))])

In [ ]:
# Make predictions on the testing data
y_pred = pipeline_clf.predict(X_test)

In [ ]:
# Evaluate the performance of the model using mean squared error and R-squared
print('Mean squared error:', mean_squared_error(y_test_clf, y_pred))
print('R-squared:', r2_score(y_test_clf, y_pred))

Mean squared error: 0.11220825852782765
R-squared: 0.5415677704068678


In [ ]:
y_test_clf

Target
20322       0
11597       0
21138       0
10376       0
4738        0
...       ...
10742       1
23085       1
5953        0
8203        1
13812       1

[5570 rows x 1 columns]

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [ ]:
with open('Classification_model.pkl', 'wb') as f:
    pickle.dump(pipeline_clf, f)

# Regression

In [ ]:
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor

In [ ]:
X_train, X_test, y_train_reg, y_test_reg = train_test_split(df_X, df_y_regression, test_size=0.2, random_state=42)

In [ ]:
y_train_reg

EMI       ELA       ROI
6939    80.148875  0.095247  0.070055
7706    27.756282  0.088475  0.024027
5549    86.018333  0.093405  0.075205
3794    60.250036  0.094214  0.052592
14331  181.679833  0.084366  0.159154
...           ...       ...       ...
21575   68.672917  0.087666  0.059984
5390    11.537501  0.088835  0.009844
860     34.545173  0.095242  0.029205
15795  100.486750  0.086434  0.087902
23654   83.333913  0.091287  0.072849

[22277 rows x 3 columns]

In [ ]:
from sklearn import ensemble

# create a pipeline
model_reg = MultiOutputRegressor(ensemble.GradientBoostingRegressor())
Regression_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    
    ('model', model_reg)
])

# fit the model
Regression_pipeline.fit(X_train, y_train_reg)

# make predictions
y_pred_reg = Regression_pipeline.predict(X_test)

# evaluate the model
mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)
print('Mean squared error:', mse)
print('R-squared:', r2)


Mean squared error: 646.3918790238341
R-squared: 0.8770374238880629


In [ ]:
y_test_reg[:1]

EMI       ELA       ROI
20322  4.650642  0.089033  0.003793

In [ ]:
y_pred_reg[0]

array([-0.74563617,  0.08928232,  0.00151711])

In [ ]:
with open('Regression_model.pkl', 'wb') as f:
    pickle.dump(Regression_pipeline, f)